# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 367f93fbb97074b731d94944ee3cb82837ed6516f13363d376122d750b08d9a3aebbdca096b6e07e4ddf198f4b06410d4c444f2b6b2b0567b4e8067fc58899b2

test:
  secret_key_base: 45989de11de8d0304e77e5512faef2ce199105a889752495296022c2a73db7d78222df0273aea59e6d5a90a70fef664a338d2f244501bf2c659b31ff765cab63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
